replicaCount: 1
labels:
  name: iris
  type: fast-api
namespace: default
autoscaling:
  enabled: false
image:
  repository: juanse77/iris-image
  tag: latest
service:
  nodeport: 32100
resources:
  limits:
    cpus: 500m
    memory: 1024M
  reservations:
    cpus: 250m
    memory: 1024M
